/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121317",
        "surface-dim": "#121317",
        "surface-bright": "#38393e",
        "surface-container-lowest": "#0d0e12",
        "surface-container-low": "#1a1b20",
        "surface-container": "#1e1f24",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343439",
        "surface-variant": "#343439",
        "on-surface": "#e3e2e8",
        "on-surface-variant": "#cbc3d7",
        "inverse-surface": "#e3e2e8",
        "inverse-on-surface": "#2f3035",
        "primary": "#d0bcff",
        "primary-container": "#a078ff",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "secondary": "#4cd7f6",
        "secondary-container": "#03b5d3",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary": "#003640",
        "on-secondary-container": "#00424e",
        "tertiary": "#ffb0cd",
        "tertiary-container": "#f751a1",
        "tertiary-fixed": "#ffd9e4",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-tertiary": "#640039",
        "outline": "#958ea0",
        "outline-variant": "#494454",
        "error": "#ffb4ab",
        "error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
